version: '3'
services:
  cloposapp:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: managementapp:php
    container_name: managementapp
    restart: unless-stopped
#    extra_hosts:
#      - host.docker.internal:host-gateway
    tty: true
    stdin_open: true
    hostname: management_docker_app
    volumes:
      - .:/var/www/html
    environment:
      CLOPOS_RUN_IN_DOCKER: '1'
    networks:
      - management.api
  clopos:
    image: mariadb:10.5.8
    container_name: management-database
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'management'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ../.management-docker-db/:/var/lib/mysql
    networks:
      - management.api
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6377:6379"
    networks:
      - management.api
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - management.api
networks:
  management.api:
    driver: bridge


